module ApplicationHelper
  def full_name(language)
    language = language.upcase
    case language
    when "EN" then "🇬🇧 English"
    when "EN-US" then "🇺🇸 English (US)"
    when "EN-GB" then "🇬🇧 English (UK)"
    when "JA" then "🇯🇵 Japanese"
    when "ZH" then "🇨🇳 Chinese"
    when "ZH-CN" then "🇨🇳 Chinese (Simplified)"
    when "ZH-TW" then "🇹🇼 Chinese (Traditional)"
    when "KO" then "🇰🇷 Korean"
    when "FR" then "🇫🇷 French"
    when "DE" then "🇩🇪 German"
    when "ES" then "🇪🇸 Spanish"
    when "ES-MX", "ES-LA" then "🇲🇽 Spanish (Latin America)"
    when "PT" then "🇵🇹 Portuguese"
    when "PT-BR" then "🇧🇷 Portuguese (Brazil)"
    when "IT" then "🇮🇹 Italian"
    when "RU" then "🇷🇺 Russian"
    when "NL" then "🇳🇱 Dutch"
    when "PL" then "🇵🇱 Polish"
    when "TR" then "🇹🇷 Turkish"
    when "CS" then "🇨🇿 Czech"
    when "DA" then "🇩🇰 Danish"
    when "EL" then "🇬🇷 Greek"
    when "FI" then "🇫🇮 Finnish"
    when "HU" then "🇭🇺 Hungarian"
    when "RO" then "🇷🇴 Romanian"
    when "SK" then "🇸🇰 Slovak"
    when "SV" then "🇸🇪 Swedish"
    when "BG" then "🇧🇬 Bulgarian"
    when "UK", "UK-UA" then "🇺🇦 Ukrainian"
    when "LT" then "🇱🇹 Lithuanian"
    when "LV" then "🇱🇻 Latvian"
    when "ET" then "🇪🇪 Estonian"
    when "SL" then "🇸🇮 Slovenian"
    when "HI" then "🇮🇳 Hindi"
    when "ID" then "🇮🇩 Indonesian"
    when "TH" then "🇹🇭 Thai"
    when "VI" then "🇻🇳 Vietnamese"
    when "HE" then "🇮🇱 Hebrew"
    when "AR" then "🇸🇦 Arabic"
    when "NO" then "🇳🇴 Norwegian"
    when "MS" then "🇲🇾 Malay"
    when "FA" then "🇮🇷 Persian (Farsi)"
    when "SW" then "🇰🇪 Swahili"
    when "AF" then "🇿🇦 Afrikaans"
    when "UR" then "🇵🇰 Urdu"
    when "TL" then "🇵🇭 Tagalog"
    when "BN" then "🇧🇩 Bengali"
    else
      language
    end
  end
end
